#!/bin/sh
#
# Starts the aes67 subsystem
#

mktempDIR(){
  prefix="pipewire"
  temp_dir=$(mktemp -d /tmp/XXXXXX)
  mv "$temp_dir" "/tmp/${prefix}.$(basename "$temp_dir")"  # Rename
  temp_dir="/tmp/${prefix}.$(basename "$temp_dir")" # Update variable
  echo "$temp_dir"
  export PIPEWIRE_RUNTIME_DIR=$temp_dir
}

startDbus(){
  dbus-daemon --system --nopidfile
  export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/dbus/system_bus_socket"
  sleep 1
}

startPipewire(){
  echo export PIPEWIRE_RUNTIME_DIR=$PIPEWIRE_RUNTIME_DIR
  pipewire &
  sleep 1
}

startAES67(){
  startDbus
  mktempDIR
  startPipewire
  # pipewire-aes67 &
  # sleep 5
  # wireplumber &
  # sleep 1
  # killall wireplumber
  # sleep 1
  # wireplumber &
  # sleep 3
  # pipewire-media-session &
}

stopAES67(){
  # killall wireplumber
#  killall pipewire-media-session
  # killall pipewire-aes67
  killall pipewire
  killall dbus-daemon
  sleep 1

  rm -rf /tmp/pipewire.*
}

case "$1" in
  start)
    echo starting aes67 subsystem
    startAES67
	;;
  stop)
    echo stopping aes67 subsystem
    stopAES67
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
