snd-soc-module-overlay-example-objs := module-overlay-example.o
obj-$(CONFIG_SND_SOC_MODULE_OVERLAY_EXAMPLE)  += snd-soc-module-overlay-example.o
dtbo-y += module-overlay-example.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
