snd-soc-module-overlay-rk3308-objs := module-overlay-rk3308.o
obj-$(CONFIG_SND_SOC_MODULE_OVERLAY_RK3308)  += snd-soc-module-overlay-rk3308.o
dtbo-y += module-overlay-rk3308.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
